name: Deploy React App with Terraform

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy React App to AWS
        uses: woragis/terraform-react@v1
        with:
          project-name: ${{ secrets.PROJECT_NAME }} # e.g., "MyReactApp"
          root-domain: ${{ secrets.ROOT_DOMAIN }} # e.g., "example.com"
          terraform-dir: ./terraform
          # Optional: aws-region: "us-west-2"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
