name: AWS Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: ./.github/actions/aws-deploy.yaml
    with:
      aws-region: us-east-1
      project-name: woragis
      root-domain: example.com
      subdomain: www
      environment: prod
      s3-bucket-name: woragis-prod-bucket
      logging-bucket-name: woragis-prod-logs
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
