name: Deploy React App

on:
  push:
    branches:
      - dev
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Terraform React Action
        uses: woragis/terraform-react@v1
        with:
          project-name: 'Woragis'
          root-domain: 'woragis.com'
          terraform-dir: './terraform'
          subdomain: 'www'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
