name: AWS Deploy

on:
  push:
    branches:
      - dev
      - main
      - staging

jobs:
  terraform-s3:
    name: Create S3 Buckets
    runs-on: ubuntu-latest
    steps:
      - name: Deploy React App Infrastructure
        uses: woragis/terraform-s3@v1
        with:
          project-name: myapp
          terraform-dir: ./terraform/s3
          aws-region: us-east-1
          s3-bucket-name: woragis-bucket-name
          logging-bucket-name: woragis-logging-bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Extract Terraform outputs
        working-directory: ./terraform/s3
        id: get_outputs
        run: |
          echo "s3_bucket_name=$(terraform output -raw s3_bucket_name)" >> $GITHUB_OUTPUT
          echo "website_endpoint=$(terraform output -raw website_endpoint)" >> $GITHUB_OUTPUT

    outputs:
      s3_bucket_name: ${{ steps.get_outputs.outputs.s3_bucket_name }}
      website_endpoint: ${{ steps.get_outputs.outputs.website_endpoint }}

  terraform-cdn:
    name: Connect CloudFront to S3 Buckets and Routes
    runs-on: ubuntu-latest
    needs: terraform-s3
    steps:
      - name: Update CDN (CloudFront)
        uses: woragis/terraform-cdn@v1
        with:
          project-name: myapp
          terraform-dir: ./terraform/cdn
          root-domain: woragis.com
          origin-domain-name: ${{ needs.terraform-s3.outputs.website_endpoint }}
          logging-bucket-domain-name: ${{ needs.terraform-s3.outputs.logging_bucket_name }}
          environment: prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Extract Terraform outputs
        working-directory: ./terraform/cdn
        id: get_outputs
        shell: bash
        run: |
          echo "cloudfront_domain_name=$(terraform output -raw cloudfront_domain_name)" >> $GITHUB_OUTPUT
          echo "cloudfront_distribution_id=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_OUTPUT
          echo "full_domain=$(terraform output -raw full_domain)" >> $GITHUB_OUTPUT
          echo "zone_id=$(terraform output -raw zone_id)" >> $GITHUB_OUTPUT

    outputs:
      cloudfront_domain_name: ${{ steps.get_outputs.outputs.cloudfront_domain_name }}
      cloudfront_distribution_id: ${{ steps.get_outputs.outputs.cloudfront_distribution_id }}
      full_domain: ${{ steps.get_outputs.outputs.full_domain }}
      zone_id: ${{ steps.get_outputs.outputs.zone_id }}

  terraform-route53:
    name: Create Routes and Certificates
    runs-on: ubuntu-latest
    needs: terraform-cdn
    steps:
      - name: Set up Route 53 DNS
        uses: woragis/terraform-route53@v1
        with:
          project-name: myapp
          root-domain: example.com
          subdomain: app
          target-domain: ${{ needs.terraform-cdn.outputs.cloudfront_domain_name }}
          target-record-type: CNAME
          terraform-dir: ./terraform/route53
          aws-region: us-east-1
          environment: prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  s3-deploy:
    name: Deploy React App to S3 Bucket
    runs-on: ubuntu-latest
    needs:
      - terraform-s3
      - terraform-cdn
      - terraform-route53
    steps:
      - name: Debug output
        run: |
          echo "S3 Bucket: ${{ needs.terraform-s3.outputs.s3_bucket_name }}"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or your desired Node version

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://${{ needs.terraform-s3.outputs.s3_bucket_name }} --delete
