name: Deploy MyApp

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: ./.github/actions/aws-deploy.yml
    with:
      aws-region: us-east-1
      project-name: myapp
      root-domain: example.com
      subdomain: app
      environment: prod
      s3-bucket-name: myapp-prod-bucket
      logging-bucket-name: myapp-prod-logs
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
